filenameTemplate: "[{rel_group}] {title} - {ep_num} [{suffix}]"
releaseGroup: CR
epNumLength: 2
fileSuffix: SIZEp
videoQuality: 720p
dubLanguage: jpn
mp4mux: false
muxSubs: false
noCleanUp: false
kStream: 1
nServer: 1
tsparts: 10
oldStreams: false
oldSubs: false
hsLang: none
dlSubs: all
useBCPtags: false
defSubLang: none
useFolder: false
proxy: false
proxy_auth: false
proxy_ssp: false
